services:
  - type: worker
    name: meduza-bot
    env: node
    plan: free
    rootDir: bot
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
